### PR TITLE
feat: support ipywidgets>8 by passing tuples to dropdown instead of dict

### PR DESCRIPTION
**Pull request by devstein**
### Description

Closes https://github.com/jupyter-incubator/sparkmagic/issues/769
Relates to https://github.com/jupyter-widgets/ipywidgets/pull/2679

[ipywidgets dropped supported for map types in 8.0.0](https://github.com/jupyter-widgets/ipywidgets/issues/1958) because drop downs should be ordered. This PR passes an ordered list of tuples to all of the references to `Dropdown` instead of a dict.

Note: `dict` support was re-added in https://github.com/jupyter-widgets/ipywidgets/pull/3557, but still think it makes sense to move to an ordered list of tuples

### Checklist
- [x] Wrote a description of my changes above 
- [x] Formatted my code with [`black`](https://black.readthedocs.io/en/stable/index.html)
- [x] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [x] Added or modified unit tests to reflect my changes
- [x] Manually tested with a notebook
- [ ] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

### CODE REVIEW

**Comment by jasongrout** [comment]
FYI, 8.0.2 adds back in support for dicts since now dicts are ordered, though it isn't advertised in the docs: https://github.com/jupyter-widgets/ipywidgets/pull/3557

**Comment by jasongrout** [comment]
> FYI, ipywidgets 8.0.2 adds back in support for dicts since now dicts are ordered, though it isn't advertised in the docs: [jupyter-widgets/ipywidgets#3557](https://github.com/jupyter-widgets/ipywidgets/pull/3557)

This is noted in https://github.com/jupyter-incubator/sparkmagic/issues/769#issuecomment-1235807047 too.

However, I think these changes look good to me, and an improvement.

**Review by jasongrout — COMMENTED** [review]
LGTM

**Comment by devstein** [comment]
Thanks for reviewing @jasongrout! I saw that `dict` support was re-added, but thought the ordered tuple is clearer, so made the change.

**Pull request merged**
