### PR TITLE
Widget prototype

### PR DESCRIPTION
**Pull request by alope107**
Not meant to be merged, just putting this here so you can see what I'm planning with the widgets @aggFTW 
Note that the widgets will not render in the github preview, but they work in a live notebook.  I'll polish this up and write the rest of the widgets today and tomorrow.

### CODE REVIEW

**Comment by aggFTW** [comment]
Awesome to see @alope107  =) I'll take a look later today. Just sent a PR myself!

**Comment by ellisonbg** [comment]
Can you post a screen shot?

On Sat, Oct 10, 2015 at 6:14 PM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Awesome to see @alope107 <https://github.com/alope107> =) I'll take a
> look later today. Just sent a PR myself!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter-incubator/sparkmagic/pull/22#issuecomment-147130023>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by alope107** [comment]
screen shot 2015-10-10 at 4 15 12 pm
Here's a screenshot of my add endpoint prototype.

**Comment by ellisonbg** [comment]
Very cool!

On Sat, Oct 10, 2015 at 7:13 PM, alope107 <notifications@github.com> wrote:

> [image: screen shot 2015-10-10 at 4 15 12 pm]
> <https://cloud.githubusercontent.com/assets/9411388/10413746/bab97fce-6f69-11e5-939d-56faa5c62d3e.png>
> Here's a screenshot of my add endpoint prototype.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter-incubator/sparkmagic/pull/22#issuecomment-147133854>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by alope107** [comment]
Work rebased and moved to #25

**Pull request closed without merging**
