### PR TITLE
Format %%info as table

### LINKED ISSUE #230: Improve output of %%info
Might want to use [this ](https://ipython.org/ipython-doc/3/config/integrating.html) to show a HTML table.

### PR DESCRIPTION
**Pull request by msftristew**
Closes #230 

Format the output of `%%info` as a table:

image

The formatting of the output of the magic `%%spark info` hasn't been updated in this PR; that will require more refactoring.

### CODE REVIEW

**Comment by aggFTW** [comment]
We lost the session config of the current session. Can you add it back please?

**Comment by aggFTW** [comment]
Should we order the applications by ID?

**Comment by aggFTW** [comment]
Or by state?

**Comment by msftristew** [comment]
Ordering by ID makes sense

**Pull request merged**
