### PR TITLE
Support newer ipykernels

### LINKED ISSUE #492: Issue with pyspark(3) kernel: TypeError: 'Future' object is not subscriptable
I am having the following issue with version 0.12.6 of sparkmagic and pyspark kernels.

```
[I 00:25:07.005 NotebookApp] Kernel started: fa701309-a461-4d32-b4da-7fccb694f1f1
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 28, in <module>
    IPKernelApp.launch_instance(kernel_class=PySparkKernel)
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-139>", line 2, in initialize
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/spark/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "/home/spark/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 23, in __init__
    language_info, session_language, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 42, in __init__
    self._load_magics_extension()
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 71, in _load_magics_extension
    log_if_error="Failed to load the Spark kernels magics library.")
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 102, in _execute_cell
    if shutdown_if_error and reply_content[u"status"] == u"error":
TypeError: 'Future' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by itamarst**
Fixes #492 

In theory this should work with both Python 2 (using ipykernel 4.10) and Python 3 (newer ipykernels).

Thanks to @jaipreet-s for the bulk of the code.

Again, would appreciate some user testing—does this work for you with Python 2? Python 3? What version ipykernel do you end up with (`pip list | grep ipykernel`).

Please REPLY WITH A COMMENT, a thumbs up isn't very informative.

### CODE REVIEW

**Comment by ericdill** [comment]
I think you also need to update hdijupyuterutils since that's also got ipykernel pinned to <5

**Comment by Tagar** [comment]
Thank you @ericdill 

Did you get a chance to test if this works correctly with newer ipykernel versions?

**Comment by itamarst** [comment]
I will try autovizwidget and see what's going on.

**Comment by Tagar** [comment]
Thank you @itamarst

**Comment by itamarst** [comment]
1. I relaxed the constraints even more, superseding #544. This should just use the latest Jupyter etc..
2. Tested autovizwidget and general usage (of Python) on Python 2 and Python 3. It worked.
3. Remaining issue is the pyspark kernel, which doesn't seem to work? Next will try to figure out why.

**Comment by itamarst** [comment]
pyspark kernel worked too once I read the README and followed the instructions :man_facepalming: 

So I'm going to merge this.

**Pull request merged**
