### PR TITLE
Fix Info Subcommand in RemoteSparkMagic

### PR DESCRIPTION
**Pull request by LinanZheng**
This PR will address the issue mentioned in https://github.com/jupyter-incubator/sparkmagic/issues/627 by enforcing both id and url arguments.

### CODE REVIEW

**Comment by LinanZheng** [comment]
@devstein My bad! Wasn't waiting for the Travis CI to finish when I submitted the PR. Will fix it later.

**Comment by LinanZheng** [comment]
@devstein Hey there! I have fixed the unit test as promised. Feel free to take a second look and let me know if something is not right. Thanks!

**Comment by itamarst** [comment]
@LinanZheng any interest in becoming maintainer? You just need to follow the code of conduct and development guidelines.

**Comment by LinanZheng** [comment]
@itamarst 
I responded to the other comment in the other MR and I will be absolutely honored to be a maintainer here. 

Side question: Where can I find the code of conduct and dev guidelines?

**Comment by itamarst** [comment]
@LinanZheng https://github.com/jupyter-incubator/sparkmagic/blob/master/CODE_OF_CONDUCT.md
https://github.com/jupyter-incubator/sparkmagic/issues/609

**Pull request merged**
