### PR TITLE
Fix formatting issue

### PR DESCRIPTION
**Pull request by Strunevskiy**
### Description
Fix formatting issue

### Checklist
- [X] Wrote a description of my changes above 
- [X] Formatted my code with [`black`](https://black.readthedocs.io/en/stable/index.html)
- [X] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [X] Added or modified unit tests to reflect my changes
- [X] Manually tested with a notebook
- [N/A] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

### CODE REVIEW

**Comment by Strunevskiy** [comment]
@devstein could you please take a look at this formatting fix, it looks like my previous PR did not have it.
I am sorry for this.

**Review by devstein — APPROVED** [review]
Beat me to it. Thanks for following up

**Comment by Strunevskiy** [comment]
@devstein  do you know why we do not run tests as part of merge or PR ?

**Comment by devstein** [comment]
@Strunevskiy No 🤔 this PR should fix it https://github.com/jupyter-incubator/sparkmagic/pull/837

**Pull request merged**
