### PR TITLE
Session Name is usable only if defined with lowercase chars

### PR DESCRIPTION
**Pull request by GauravAjaySingh**
The Session name should work for mixed case characters in addition to lowercase chars as well.

Screen Shot 2019-03-22 at 4 27 47 PM

### CODE REVIEW

**Comment by Tagar** [comment]
@itamarst seems to be a straight-forward fix.. any chance to include this into `0.12.9` release?
thank you

**Comment by itamarst** [comment]
0.12.9 is out :) Could do in next one. I'm probably going to be spending a little less time on SparkMagic in next few weeks since seems like critical problems have been fixed.

**Comment by itamarst** [comment]
@GauravAjaySingh why did you close this?

**Comment by devstein** [comment]
@itamarst Any reason to not merge this fix?

**Comment by itamarst** [comment]
Would want the tests passing, at least.

**Comment by itamarst** [comment]
OK tests are passing, so sure if you want—add a changelog entry afterwards, maybe?

**Comment by devstein** [comment]
How should I format the changelog entry? What will the next release be?

**Comment by itamarst** [comment]
0.15.0, I guess? You can see format I used here: https://github.com/jupyter-incubator/sparkmagic/blob/master/CHANGELOG.md

Thanks for taking the time to work on this!

**Comment by itamarst** [comment]
@GauravAjaySingh any interest in becoming a maintainer?

You'd need to agree to the Code of Conduct, and try to keep code quality up.

**Pull request merged**
