### PR TITLE
Change import paths for dataerror

### PR DESCRIPTION
**Pull request by GaspardBT**
### Description
Fixes import paths after pandas latest release (1.5.0)
DataError is now in `pandas.errors` change [here](https://github.com/pandas-dev/pandas/pull/47047/files)
### Checklist
- [x] Wrote a description of my changes above 
- [x] Formatted my code with [`black`](https://black.readthedocs.io/en/stable/index.html)
- [ ] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [ ] Added or modified unit tests to reflect my changes
- [x] Manually tested with a notebook
- [ ] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

### CODE REVIEW

**Comment by lucasdurand** [comment]
This change would require the user to be on `pandas>=1.5.0` , but that isn’t specified in the package requirements, so this change should also:
1. Pin `pandas>=1.5.0` in the setup.py (which I’m thinking we don’t want to do)
2. Instead, extend the existing try/except block to handle the new `DataError` location, while still supporting the existing fallbacks

**Comment by GaspardBT** [comment]
Thanks for the review 🙇 
I make the modification for the second option, is it right?

**Review by devstein — APPROVED** [review]
@GaspardBT Thank you for contributing! LGTM 👍

**Comment by devstein** [comment]
and @lucasdurand thank you for reviewing!

**Pull request merged**
