### PR TITLE
Show progress for long running operations #147

### PR DESCRIPTION
**Pull request by tps-supership**
Hi,

I don't know if i am following any proper contribution protocols here.

Please find a simple implementation for the issue 'Show progress for long running operations #147'.

Tested with livy server 0.4.0 and 0.5.0

### CODE REVIEW

**Comment by tps-supership** [comment]
May i ask you to point me how i can run the tests locally?

All the best

**Comment by tps-supership** [comment]
Hi @aggFTW 

I am seeing some tests fail even on the vanilla master branch.
For instance:
```
======================================================================
FAIL: sparkmagic.tests.test_remotesparkmagics.test_add_sessions_command_exception
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jovyan/sparkmagic/sparkmagic/tests/test_remotesparkmagics.py", line 114, in test_add_sessions_command_exception
    False, {"kind": "pyspark"})
  File "/opt/conda/lib/python3.6/site-packages/mock/mock.py", line 948, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/mock/mock.py", line 937, in assert_called_with
    six.raise_from(AssertionError(_error_message(cause)), cause)
  File "<string>", line 2, in raise_from
AssertionError: Expected call: add_session('name', <sparkmagic.livyclientlib.endpoint.Endpoint object at 0x7f7a2db4d518>, False, {'kind': 'pyspark'})
Actual call: add_session('name', <sparkmagic.livyclientlib.endpoint.Endpoint object at 0x7f7a2db43320>, False, {'driverMemory': '1000M', 'executorCores': 2, 'kind': 'pyspark'})

----------------------------------------------------------------------
```
Or
```
======================================================================
ERROR: sparkmagic.tests.test_sparkkernelbase.test_delete_session
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/nose/case.py", line 268, in setUp
    try_run(self.test, names)
  File "/opt/conda/lib/python3.6/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/jovyan/sparkmagic/sparkmagic/tests/test_sparkkernelbase.py", line 26, in _setup
    kernel = TestSparkKernel()
  File "/home/jovyan/sparkmagic/sparkmagic/tests/test_sparkkernelbase.py", line 20, in __init__
    **kwargs)
  File "/home/jovyan/sparkmagic/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 27, in __init__
    super(SparkKernelBase, self).__init__(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 46, in __init__
    kernel      = self,
  File "/opt/conda/lib/python3.6/site-packages/traitlets/config/configurable.py", line 423, in instance
    '%s are being created.' % cls.__name__
traitlets.config.configurable.MultipleInstanceError: Multiple incompatible subclass instances of ZMQInteractiveShell are being created.

======================================================================
```

Am i working on a wrong branch?

**Comment by thesuperzapper** [comment]
@aggFTW @tps-supership 

While I don't know if this PR is the best implementation of it, we do need to implement this feature. 

See #455

**Comment by juliusvonkohout** [comment]
Superseeded by #541 please close @itamarst

**Pull request closed without merging**
