### PR TITLE
delete obsolete pyspark3kernel

### PR DESCRIPTION
**Pull request by juliusvonkohout**
@itamarst you forgot to remove the pyspark3kernel. There should only be pysparkkernel now and the livy/spark python version is handled by
``` bash
%%configure -f
{"conf":{
    "spark.pyspark.python":"python3",
}
```
if spark.pyspark.python=python3 is not already the default on the cluster. https://github.com/apache/incubator-livy/commit/64d71aa757a93518427f315e908dcf54373948b2

### CODE REVIEW

**Comment by apetresc** [comment]
Appears to work in Docker, thank you :+1:

**Comment by juliusvonkohout** [comment]
> Appears to work in Docker, thank you +1

Thanks @apetresc can you also have a look at #544 ?

**Comment by itamarst** [comment]
@juliusvonkohout 

Would you be interested in getting commit access to the repo and becoming a maintainer?

You would need to:

1. Agree to the code of conduct.
2. Follow best practices (automated tests, manual test, docs, review).

**Comment by juliusvonkohout** [comment]
> @juliusvonkohout
> 
> Would you be interested in getting commit access to the repo and becoming a maintainer?
> 
> You would need to:
> 
>     1. Agree to the code of conduct.
> 
>     2. Follow best practices (automated tests, manual test, docs, review).

Well i think that is a good idea, although i do not know how much spare time i will have to help.

**Pull request merged**
