### PR TITLE
add magic for matplotlib display(pyspark or pyspark3)

### PR DESCRIPTION
**Pull request by wangqiaoshi**
now sparkmagic must be pass data to local  then matplot.  
it is expensive if the data is big

### CODE REVIEW

**Comment by Tagar** [comment]
This is a great improvement .

A screenshot of an example usage would be nice.. or sparkmagic documentation updated.

Thanks!

**Comment by wangqiaoshi** [comment]
> This is a great improvement .
> 
> A screenshot of an example usage would be nice.. or sparkmagic documentation updated.
> 
> Thanks!

ok,i add screenshot.

**Comment by Tagar** [comment]
Thanks @wangqiaoshi 

@apetresc could you please help review and hopefully merge this? 

It seems to be a great improvement for larger visualizations - so viz can happen on Spark driver and then only visualization itself will have to travel over network to Jupyter.

**Comment by brookwc** [comment]
@Tagar @apetresc hey! This diff is quite useful to us. Has it been merged into trunk?

**Comment by Tagar** [comment]
@itamarst can this be part of the newer release you're preparing ? 
thank you

**Comment by itamarst** [comment]
Merging to branch so I can iterate on this.

**Comment by itamarst** [comment]
Hi, could you all try the version in #552? Adds support for usage in normal notebooks, not just the PySpark kernel.

**Pull request merged**
