### PR TITLE
Add ability to choose a y axis with pie chart

### PR DESCRIPTION
**Pull request by aggFTW**
We've learned from users that when doing a query like:

```
SELECT label, COUNT(*) FROM table
```

they expect the pie chart to show proportional areas by the count. Seeing that all labels will get the same amount of area, which is the current behavior, is counterintuitive for them.

That said, previous functionality can still be achieved by selecting None as the Y encoding.

### CODE REVIEW

**Comment by aggFTW** [comment]
Selecting a Y axis:

y_selected

Previous functionality:

y_not_selected

**Comment by msftristew** [comment]
My only worry is that I don't know if anyone will be able to come up with the "secret recipe" for producing the second pie graph.  FWIW, even if I knew I wanted to construct exactly that pie graph, I would never be able to guess that the way to get it would be by selecting X: date, Y: null, Func: Sum.

**Comment by aggFTW** [comment]
1. Any Func works to get that graph, not only Sum.
2. Your discoverability argument applies to any other graph really, no? I have a hard time creating charts in any other number of products I've used that make charting easy. Do you have a particular suggestion on how to make it better?

**Comment by msftristew** [comment]
No particular suggestion for improvement.  To me, if I were going to try to make this graph, I would choose:

X: date
Y: date
Func: count

However, the implementation to make that work probably wouldn't be simple.

LGTM, feel free to merge as-is, but I think this question is worth investigating further.  (Possible approach: poll some users about how they expect the UI to work, find the most common response(s), and ensure that set of options works the way people expect it to)

**Pull request merged**
