### PR TITLE
Fix missing url passing when using a custom authenticator

### PR DESCRIPTION
**Pull request by gthomas-slack**
### Description
Fixes a bug with passing the url from the configuration when using a Custom Authenticator. Fixes https://github.com/jupyter-incubator/sparkmagic/issues/683 - see this issue for more details.

### Checklist
- [x] Wrote a description of my changes above 
- [ ] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [ ] Added or modified unit tests to reflect my changes
- [x] Manually tested with a notebook
- [ ] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

### CODE REVIEW

**Review by devstein — APPROVED** [review]
Thanks for contributing! I'll include this in a new patch release as soon as I can

**Comment by itamarst** [comment]
Unit test would be nice too, @gthomas-slack.

Also, would you be interested in being given commit access? You'd have to agree to following the development process, and the code of conduct.

**Comment by VasuBhog** [comment]
Would this be patched into the 0.17.0 version or released with the next 0.18.0 release? What would be the timeframe for either option?

**Comment by devstein** [comment]
@VasuBhog It will be a new patch release `0.17.1`. I'll release it in the next few hours

**Pull request merged**
