### PR TITLE
Updated pandas to 2.x

### PR DESCRIPTION
**Pull request by venu1412**
Relates to https://github.com/jupyter-incubator/sparkmagic/issues/811

### Description
Updated pandas to 2.x

### Checklist
- [X] Wrote a description of my changes above 
- [X] Formatted my code with [`black`](https://black.readthedocs.io/en/stable/index.html)
- [X] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [X] Added or modified unit tests to reflect my changes
- [X] Manually tested with a notebook
- [X] If adding a feature, there is an example notebook and/or documentation in the `README.md` file

### CODE REVIEW

**Comment by venu1412** [comment]
@devstein Can anyone review the PR?

**Review by devstein — APPROVED** [review]
@venu1412 thank you for contributing! This hugely helpful to the community

**Comment by venu1412** [comment]
@devstein Do we have any planned release? Can we release any alpha/beta package with the all the recent changes?

**Comment by venu1412** [comment]
@devstein Do we have any planned release? If so can you please share the details.

**Comment by devstein** [comment]
Hi, yes hoping to do a release this week. On Nov 3, 2024, at 7:41 PM, venu1412 ***@***.***> wrote:﻿
@devstein Do we have any planned release? If so can you please share the details.

**Pull request merged**
