### PR TITLE
Support text/html MIME type.

### PR DESCRIPTION
**Pull request by suhsteve**
This PR introduces support for the `text/html` MIME type and addresses #562 

https://github.com/jupyter-incubator/sparkmagic/blob/cf06e20553df2e2157d5d95db6a167a62145963b/sparkmagic/sparkmagic/livyclientlib/command.py#L85-L93

The above has been modified to return the MIME type as part of its return values.

https://github.com/jupyter-incubator/sparkmagic/blob/161b681e272a1dab6fc60547ea771305b84295d7/sparkmagic/sparkmagic/magics/sparkmagicsbase.py#L47-L50

`sparkmagicbase.py` has been modified to call `self.ipython_display.html` if the MIME type is `text/html`

### CODE REVIEW

**Comment by suhsteve** [comment]
cc: @rapoth, @imback82

**Comment by imback82** [comment]
@itamarst can you help reviewing this? Thanks!

**Comment by itamarst** [comment]
The PR looks fine, my main question is under what circumstances does livy return html?

**Comment by imback82** [comment]
We are working on C# interpreter inside the Livy (for [.NET for Apache Spark](https://github.com/dotnet/spark)) and the .NET REPL supports html mimetype for a richer experience.

**Comment by mitchellsayer** [comment]
@itamarst I'm building a visualization tool using Folium and would also find this a very useful feature.

**Comment by mitchellsayer** [comment]
@itamarst Is this ready to merge?

**Comment by itamarst** [comment]
Yeah.

**Comment by itamarst** [comment]
Thank you for the PR!

**Comment by mitchellsayer** [comment]
I am confused. How do you make a cell return data with type html? Is there a special sparkmagic command or some specific way of wrapping the cell output? @imback82

**Comment by imback82** [comment]
@mitchellsayer [.NET for Apache Spark](https://github.com/dotnet/spark) will be using [dotnet/try](https://github.com/dotnet/try) as REPL and the REPL can return the result as text/html mimetype for richer experience. Does this make sense?

**Comment by itamarst** [comment]
@suhsteve 

Would you be interested in getting commit access to the repo and becoming a maintainer?

You need to:

1. Agree to the code of conduct.
2. Follow best practices (automated tests, manual test, docs, reviews).

**Comment by suhsteve** [comment]
@itamarst Thanks for the opportunity!  I'd be very interested in helping maintain this repo.

**Pull request merged**
