### PR TITLE
Pin ipykernel<6.0.0

### LINKED ISSUE #492: Issue with pyspark(3) kernel: TypeError: 'Future' object is not subscriptable
I am having the following issue with version 0.12.6 of sparkmagic and pyspark kernels.

```
[I 00:25:07.005 NotebookApp] Kernel started: fa701309-a461-4d32-b4da-7fccb694f1f1
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 28, in <module>
    IPKernelApp.launch_instance(kernel_class=PySparkKernel)
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-139>", line 2, in initialize
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/spark/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "/home/spark/.local/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "/home/spark/.local/lib/python3.5/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/pysparkkernel/pysparkkernel.py", line 23, in __init__
    language_info, session_language, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 42, in __init__
    self._load_magics_extension()
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 71, in _load_magics_extension
    log_if_error="Failed to load the Spark kernels magics library.")
  File "/usr/local/lib/python3.5/dist-packages/sparkmagic/kernels/wrapperkernel/sparkkernelbase.py", line 102, in _execute_cell
    if shutdown_if_error and reply_content[u"status"] == u"error":
TypeError: 'Future' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by devstein**
Closes #492 

### Description

Changes to the async behavior in [IPykernel >=6.0.0](https://github.com/ipython/ipykernel/releases) causes connection issues with the Sparkmagic (Py)Spark kernels. This pins the dependency while I find the root cause of the breaking change. 

- Pins `ipykernel<6.0.0`
- Removes more references to Python 2
- Runs `black` formatter

### Checklist
- [x] Wrote a description of my changes above 
- [x] Added a bullet point for my changes to the top of the `CHANGELOG.md` file
- [x] Manually tested with a notebook

### CODE REVIEW

**Review by itamarst — APPROVED** [review]
Seems fine assuming tests pass.

**Comment by devstein** [comment]
@itamarst CI is broken because of a Travis CI migration (see below). I'm going to reach out to the maintainer of the `pip` package, so I can migrate to GH Actions

>Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by Carreau** [comment]
Thanks seem fine to me, I do have access to PyPI as a maintainer, though I believe I can only upload as I don't have access to any settings panels.

One caveat for this fix: now that pip has a resolver, once this get published, pip can decide that the solution is to not upgrade sparkmagic; I've seen similar behavior in the wild, so we might have to yank

**Comment by itamarst** [comment]
Yeah, probably need to:

1. Switch to Github Actions (GHA).
2. Generate new PyPI access token, and add it to GHA for auto-release-on-tag, like Travis currently does.

**Comment by devstein** [comment]
@itamarst Agreed.

> Thanks seem fine to me, I do have access to PyPI as a maintainer, though I believe I can only upload as I don't have access to any settings panels.

@Carreau Do you have access to generate a PyPI access token? If so, can you generate a new token and set it as an environment variable for the `sparkmagic` repo? I

**Comment by Carreau** [comment]
I believe this is now done with a repository secret.

Do you know who hdinsightmsftagu on PyPI is ? Or how to contact them ? Otherwise we can make a request to PyPI maintainer to transfer ownership – it should not be too hard as I'm already maintainer.

**Comment by Carreau** [comment]
I've personally Pinged Briand and Min to see if they have access, otherwise
I'll ask PyPI.

**Comment by Carreau** [comment]
I have an update and we might be able to get everyone as an owner in a week or so - some people are travelling and put their work notification off.

**Comment by devstein** [comment]
@Carreau Amazing, thank you for all the help on this.

**Comment by Carreau** [comment]
> @Carreau Amazing, thank you for all the help on this.

No problem, thank you for working on this. We are also working on making sure that access to resources is managed in a better way.

Do you also have a PyPI username, I supposed it will not be a problem to add you once we get back ownership.

**Comment by devstein** [comment]
@Carreau https://pypi.org/user/devstein/

**Comment by mrinmoyprasad** [comment]
Hi @devstein - do you think my issue [here](https://github.com/jupyter-incubator/sparkmagic/issues/722
) could be related to the bug your PR is addressing?

**Comment by devstein** [comment]
@mrinmoyprasad Hard to say without investigating further. Would you mind trying to reproduce to verify after the next release?

**Comment by devstein** [comment]
@Carreau I'm having [issues publishing the packages](https://github.com/jupyter-incubator/sparkmagic/runs/3345842919?check_suite_focus=true). The error message indicates an invalid token, here are the [probably root causes
](https://github.com/pypa/warehouse/issues/9018)

Any ideas what could be wrong with the token? Let me know if I can help. 

```bash
Upload failed (403): Invalid API Token: InvalidMacaroon('invalid macaroon signature')
error: Upload failed (403): Invalid API Token: InvalidMacaroon('invalid macaroon signature')
Error: Process completed with exit code 1.

```

**Comment by Carreau** [comment]
I've updated the token, and you should have received an invite.

**Comment by mrinmoyprasad** [comment]
> @mrinmoyprasad Hard to say without investigating further. Would you mind trying to reproduce to verify after the next release?

Sure thing, as soon as 0.19.1 is published, I can verify and let you know! Thank you

**Comment by devstein** [comment]
@Carreau Thanks! I now have access to[sparkmagic](https://pypi.org/project/sparkmagic/); however, I discovered the source of the error `403` is that the token is only valid for [sparkmagic](https://pypi.org/project/sparkmagic/) and not [hdijupyterutils](https://pypi.org/project/hdijupyterutils/) nor [autovizwidget](https://pypi.org/project/autovizwidget/). 

@ellisonbg is the only one with access to [hdijupyterutils](https://pypi.org/project/hdijupyterutils/) and [autovizwidget](https://pypi.org/project/autovizwidget/). Are you able to reach out to him?

**Comment by Carreau** [comment]
I'll see what I can do, though I'll be offline until next Wednesday.

**Comment by Carreau** [comment]
There should now be 3 new tokens : PYPI_TOKEN_AUTOVIZWIDGET, PYPI_TOKEN_HDIJUPYTERUTILS, PYPI_TOKEN_SPARKMAGIC with upload access to corresponding repos.

**Pull request merged**
