### PR TITLE
Update pandas version

### PR DESCRIPTION
**Pull request by ektasharma4**
### Description
Update pandas version and the test that fails here https://github.com/jupyter-incubator/sparkmagic/issues/811#issuecomment-1728119514

### CODE REVIEW

**Comment by ektasharma4** [comment]
@devstein could someone approve the workflows for this PR?

**Comment by rolweber** [comment]
ping?

**Comment by venu1412** [comment]
We are also in process of upgrading to panda's. Can this change be reviewed/merged and released?

**Comment by c2zwdjnlcg** [comment]
Don't all the requirements.txt files need to be updated too?

**Comment by venu1412** [comment]
https://github.com/jupyter-incubator/sparkmagic/blob/master/autovizwidget/requirements.txt#L5-L5
https://github.com/jupyter-incubator/sparkmagic/blob/master/hdijupyterutils/requirements.txt#L5-L5
https://github.com/jupyter-incubator/sparkmagic/blob/master/sparkmagic/requirements.txt#L4-L4 

etc...

**Comment by rolweber** [comment]
Afaik, the creator of this PR changed job roles, so will not be pursuing this.
Somebody else will have to create a new PR with the suggested improvements.

**Pull request closed without merging**
